@startuml clases

hide empty members
skinparam linetype polyline
skinparam arrowLollipopColor #ADD1B2

MainView -right(0- MainPresenter : IMainContract.Presenter
MainView -right0)- MainPresenter : IMainContract.View
MainView -up..-> InfoView : <<use>>
MainView -down..> DetailsView : <<use>>
MainPresenter -right(0- GasolinerasRepository : IGasolinerasRepository


class MainPresenter {
    -load()
}

interface IMainContract#View {
    + init()
    + getGasolinerasRepository() : IGasolinerasRepository
    + showStations(List<Gasolinera> stations)
    + showLoadCorrect(int stations)
    + showLoadError()
    + showInfoMessage(String message)
    + showStationDetails(Gasolinera station)
    + showInfoActivity()
    + showFiltersPopUp()
    + showFiltersPopUpFuelTypesSelector(List<Selection> selections)
    + showFiltersPopUpBrandSelector(List<Selection> selections)
    + updateFiltersPopupTextViewsSelections(String fuelTypes, String fuelBrands)
    + updateFiltersPopupTextViewsMaxPrice(float maxPrice)
    + updateFiltersPopUpFuelTypesSelection(int position, boolean value)
    + updateFiltersPopUpBrandsSelection(int position, boolean value)
    + closeFiltersPopUp()
}

interface IMainContract#Presenter {
    + init(View view)
    + onStationClicked(Gasolinera station)
    + onMenuInfoClicked()
    + onFiltersClicked()
    + onFiltersPopUpFuelTypesSelected()
    + onFiltersPopUpBrandsSelected()
    + onFiltersPopUpFuelTypesOneSelected(int index)
    + onFiltersPopUpBrandsAccepted()
    + onFiltersPopUpMaxPriceAccepted(float maxPrice)
    + onFiltersPopUpCancelClicked()
    + onFiltersPopUpAcceptClicked()
    + onFiltersPopUpClearFiltersClicked()
}

interface IGasolinerasRepository {
    + requestGasolineras(ICallBack cb, String ccaa)
}

interface ICallBack {
    + onSuccess(List<Gasolinera> gasolineras)
    + onFailure(Throwable e)
}


@enduml